name: creatorsofyeah
favicon: null
layout_spectrum: 0.98932
typography_spectrum: 0.62977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9469964941963553
  lightness: 0.6442159726284444
  saturation: 0.9282694621942937
  rhythmicContrast: 0.4286903452593833
purpose: []
